apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: malleus
build:
  artifacts:
    - image: ehharvey/malleus-app
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/malleus.yaml
    - k8s/postgresql.yaml
    - k8s/grafana.yaml
    - k8s/loki.yaml