---
# Minio Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels: { app: minio }
  template:
    metadata:
      labels: { app: minio }
    spec:
      containers:
        - name: minio
          image: minio/minio
          command:
            - sh
            - -c
            - mkdir -p /data/loki-data && mkdir -p /data/loki-ruler && minio server /data
          env:
            - name: MINIO_ROOT_USER
              value: loki
            - name: MINIO_ROOT_PASSWORD
              value: supersecret
          ports:
            - name: http
              containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
                claimName: minio-pvc

---
# Minio Service
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: http
  selector:
    app: minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Loki common ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_address: 0.0.0.0
      http_listen_port: 3100

    schema_config:
      configs:
        - from: 2023-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h

    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        s3:
          endpoint: minio:9000
          insecure: true
          bucketnames: loki-data
          access_key_id: loki
          secret_access_key: supersecret
          s3forcepathstyle: true

    ruler:
      storage:
        s3:
          bucketnames: loki-ruler

    compactor:
      working_directory: /tmp/compactor

---
# Loki backend (compactor/querier)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels: { app: loki }
  template:
    metadata:
      labels: { app: loki }
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args:
            - "-config.file=/etc/loki/config.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: cfg
              mountPath: /etc/loki
      volumes:
        - name: cfg
          configMap:
            name: loki-config

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
      name: http
  selector:
    app: loki