apiVersion: v1
kind: Service
metadata:
  name: malleus-service
spec:
  selector:
    app: malleus
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malleus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: malleus
  template:
    metadata:
      labels:
        app: malleus
    spec:
      containers:
        - name: app
          image: ehharvey/malleus-app
          ports:
            - containerPort: 8080