package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/ehharvey/malleus/internal/glue"
	"github.com/ehharvey/malleus/internal/graph"
	"github.com/ehharvey/malleus/internal/graph/model"
	"github.com/ehharvey/malleus/internal/inventory"
	"github.com/ehharvey/malleus/internal/outcome"
)

// CreateDomain is the resolver for the createDomain field.
func (r *mutationResolver) CreateDomain(ctx context.Context, input model.NewDomain) (*model.Domain, error) {
	createDomainParams := inventory.CreateDomainParams{
		Name: input.Name,
	}

	result := r.InventoryService.CreateDomain(
		ctx,
		createDomainParams,
		outcome.ValidationDetailLevel(outcome.ValidationReturnOnlyFailures),
	)

	// TODO: logging

	return glue.ServiceResultToGraphql(result, glue.DomainModelToGraphql)
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
